name: Code Standards & Quality

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "18.x"
      run-build:
        type: boolean
        default: false

jobs:
  build:
    name: Check Code standards & Quality
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔎 Lint code
        run: npm run lint

      - name: 📝 Checking code format
        run: npm run format:check

      - name: 💪 Type Checking
        run: npx astro check

      - name: 🚀 Build the project
        if: ${{ inputs.run-build }}
        run: npm run build
