name: Code Standards & Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - "src/**"
      - "public/**"
      - "astro.config.ts"
      - "tailwind.config.cjs"
      - "tsconfig.json"
      - "eslint.config.mjs"
      - "remark-collapse.d.ts"

jobs:
  code_quality:
    strategy:
      matrix:
        node-versions: [18.x]

    uses: ./.github/workflows/code-standards-checks.yml
    with:
      node-version: ${{ matrix.node-versions }}
      run-build: true
