name: Deploy to Github Pages

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "public/**"
      - "astro.config.ts"
      - "tailwind.config.cjs"
      - "tsconfig.json"
      - "eslint.config.mjs"
      - "remark-collapse.d.ts"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  code_quality:
    uses: ./.github/workflows/code-standards-checks.yml
    with:
      node-version: "18.x"

  unit-tests:
    uses: ./.github/workflows/tests.yml
    with:
      node-version: "18.x"

  build:
    needs: [code_quality, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v4

      - name: Install, build, and upload site
        uses: withastro/action@v3
        with:
          node-version: "18.x"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
