name: Run Tests

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "18.x"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔬 Run Unit Tests
        run: npm test
